name: rice_drop
description: Self Service Kiosk with Square Point of Sale API.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"

dependencies:
  auto_route: ^6.0.1
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.2
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  mockito: ^5.4.2
  riverpod: ^2.3.2
  url_launcher: ^6.1.10
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^6.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pictures/
    - assets/logo/Rice Drop Logo.png

  fonts:
    - family: Rhodesia
      fonts:
        - asset: assets/fonts/Rhodesia-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
